### ISSUE TITLE
ONNX inference version 11.9 is not correct.

### ISSUE THREAD

**Issue by JsonSadler** [vita-epfl/openpifpaf#305]
Hi guys, 

We were able to inference using exported ONNX in version 10.0 (here: #145  in [this comment](https://github.com/vita-epfl/openpifpaf/issues/145#issuecomment-706536165) by @undefined-references ), but now using your 11.9 version, I can not make it work, I tested everything, my decode, my input (was slightly different but no worries, I dumped torch's model input and fed it to the ONNX model, still gives wrong answers which are naturally slightly different due to slight differences in input). The problem is that outputs for bounding boxes are terribly low, the whole fields are terribly different, and I do not know how to track the problem. 

Do you test your exported ONNX in every version? Would you please provide your inference code? Should I do anything special in exporting ONNX for 11.9?

**Comment by svenkreiss** [comment]
Starting in v0.12 (the code that is currently in the dev branch), we test onnx export continuously. There is a full cycle test where the prediction outputs are compared between the pytorch model and inference with onnxruntime. This version also drastically simplifies the onnx graph for the heads.

Test case: https://github.com/vita-epfl/openpifpaf/blob/53287968e81cd052006175b13b931631da1d03ff/tests/test_onnx_export.py#L34

**Comment by undefined-references** [comment]
Hi @svenkreiss,

Thank you for the explanation, we used v0.12a4 and the problem with inference module is solved. But the inference time on gpu (2080) was around 600 ms. I tried the simplified version of onnx but it didn't have any significant improvement on inference speed. So I tried to add --optimize to the export module and I got this error:
```
  File "/usr/local/lib/python3.6/dist-packages/openpifpaf/export_onnx.py", line 91, in optimize                                                               
    optimized_model = onnx.optimizer.optimize(model)                                                                                                          
  File "/usr/local/lib/python3.6/dist-packages/onnx/optimizer.py", line 55, in optimize                                                                       
    optimized_model_str = C.optimize(model_str, passes)                                                                                                       
IndexError: Input base_net.input_block.0.weight is undefined!
```
Have you measured the inference time? or any advise for this?

**Comment by svenkreiss** [comment]
Hi @undefined-references , I don't use ONNX and TensorRT myself much and I have no timing info. The timing of our models is still the same or better from what is listed in the [Guide](https://vita-epfl.github.io/openpifpaf/dev/intro.html#pre-trained-models) when you use inference with pytorch, i.e. around 50ms. I have also played with a CoreML export that runs in real-time on the iPhone. If you evaluate on a very large image without rescaling, things get slower. What's your image size? All our numbers (timing and precision) are for the image's longer edge being 641px.
